
.include "mapa.h.s"
.include "mapas.h.s"

;;antes de la direcciona del mapa debe haber una referencia al siguiente
mapa_7_tamano: .dw #0x1212
mapa_7_siguiente: .dw #mapa_8
mapa_7::
;;SIZE x = 18 y = 18
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloAscensor, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloHueco, #mapa_simboloJugador, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio