
.include "mapa.h.s"
.include "mapas.h.s"

;;antes de la direcciona del mapa debe haber una referencia al siguiente
mapa_8_tamano: .dw #0x1414
mapa_8_siguiente: .dw #mapa_1
mapa_8::
;;SIZE x = 20 y = 20
    .db #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloAscensor, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloJugador, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHealthUp, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloHueco, #mapa_simboloEnemigo1, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloPared, #mapa_simboloVacio
    .db #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio, #mapa_simboloVacio
